name: Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: rustfmt, clippy
    - name: Build
      run: cargo build --release
    - name: Upload to release
      uses: JasonEtco/upload-to-release@master
      with:
        args: ./target/release/bust
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
